[package]
name = "rerun-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
ipc = { path = "../ipc" }
rerun = { version = "0.23.3", features = ["nasm", "sdk"], default-features = false }
rerun-ipc-common.workspace=true
serde = { version = "1.0", features = ["derive"] }
ctrlc = "3.4"
