[package]
name = "rerun-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
iceoryx2 = "0.6.1"
rerun = { version = "0.23.3", features = ["nasm", "sdk"], default-features = false }
rerun-ipc-common.workspace=true
serde = { version = "1.0", features = ["derive"] }
