[tasks.build_lunasim]
workspace = false
command = "cargo"
args = ["build", "-p", "lunasim-lib", "--release"]

[tasks.build_lunabase]
workspace = false
command = "cargo"
args = ["build", "-p", "lunabase-lib", "--release"]

[tasks.build_lunabase_prod]
workspace = false
command = "cargo"
args = ["build", "-p", "lunabase-lib", "--release", "--features=production"]

[tasks.build_lunabase_prodx]
workspace = false
command = "cargo"
args = ["build", "-p", "lunabase-lib", "--release", "--features=extended"]

[tasks.godot]
workspace = false
dependencies = [
    "build_lunabase",
    "build_lunasim"
]

[tasks.sim]
workspace = false
command = "cargo"
args = ["run", "-p", "lunabot", "--", "sim"]
dependencies = [
    "build_lunasim",
]

[tasks.main]
workspace = false
command = "cargo"
args = ["run", "--features=production", "-p", "lunabot", "--", "main"]

[tasks.clean]
workspace = false
command = "cargo"
args = ["run", "-p", "lunabot", "--", "clean"]

[tasks.import_lunabase]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "--import"]

[tasks.lunabase]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "-d"]
dependencies = [
    "build_lunabase",
    "import_lunabase",
]

[tasks.lunabase_prod]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "-d"]
dependencies = [
    "build_lunabase_prod",
    "import_lunabase",
]

[tasks.lunabase_prodx]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "-d"]
dependencies = [
    "build_lunabase_prodx",
    "import_lunabase",
]

[tasks.edit_lunasim]
workspace = false
command = "godot"
args = ["--path", "godot/lunasim", "-e"]

[tasks.edit_lunabase]
workspace = false
command = "godot"
args = ["--path", "godot/lunabase", "-e"]