[package]
name = "imu-calib"
version = "0.1.0"
edition = "2024"

[dependencies]
optimization = "0.2.0"
nalgebra.workspace = true
approx = "0.5.1"
imu-fusion = "0.2.5"


[dev-dependencies]
rand = "0.9.0"