[package]
name = "lunabot-ai-common"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcode.workspace = true
bytemuck.workspace = true
common = { path = "../common" }
embedded_common = { path = "../../embedded/embedded_common" }
nalgebra.workspace = true
