[Main]
robot_layout = "robot-layout/lunabot.json"

[Main.rerun_viz."Log"."Minimal"]

[Main.cameras."pci-0000:34:00.3-usb-0:4:1.0"]
link_name = "left_arm_camera"
focal_length_x_px = 1100
focal_length_y_px = 1100
stream_index = 0

[Main.cameras."pci-0000:34:00.4-usb-0:2.4:1.0"]
link_name = "right_arm_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 2

[Main.cameras."pci-0000:35:00.3-usb-0:1.3:1.0"]
link_name = "low_left_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 3

[Main.cameras."pci-0000:35:00.3-usb-0:1.4:1.0"]
link_name = "low_right_camera"
focal_length_x_px = 1100
focal_length_y_px = 1100
stream_index = 5

[Main.cameras."pci-0000:35:00.0-usb-0:1:1.0"]
link_name = "back_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 7

[Main.depth_cameras."309622300683"]
link_name = "upper_depth_camera"
stream_index = 1

[Main.depth_cameras."044422250424"]
link_name = "lower_depth_camera"
stream_index = 4

[Main.apriltags."1"]
tag_position = [0.0, 0.6477, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.104775

[Main.apriltags."13"]
tag_position = [-1.83, 0.75, 0.127]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.15

[Main.apriltags."26"]
tag_position = [0.0, 0.0, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.152

[Main.v3pico]
serial = "1"
[[Main.v3pico.imus]]
link_name = "imu0"

[[Main.v3pico.imus]]
link_name = "imu1"

[[Main.v3pico.imus]]
link_name = "imu2"

[[Main.v3pico.imus]]
link_name = "imu3"

[Main.vesc]
speed_multiplier = 2250.0

[[Main.vesc.pairs]]
id1 = 75
id2 = 110
mask1 = "Right"
mask2 = "Right"

[[Main.vesc.pairs]]
id1 = 63
id2 = 74
mask1 = "Left"
mask2 = "Left"
