[Main]
robot_layout = "robot-layout/lunabot.json"

[Main.rerun_viz]
Grpc = [
  "Minimal",
  "rerun+http://192.168.0.113:9876/proxy",
]

[Main.cameras."pci-0000:34:00.3-usb-0:4:1.0"]
link_name = "left_arm_camera"
focal_length_x_px = 1100
focal_length_y_px = 1100
# stream_index = 0

[Main.cameras."pci-0000:35:00.0-usb-0:1:1.0"]
link_name = "right_arm_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 2

[Main.cameras."pci-0000:35:00.3-usb-0:1.3:1.0"]
link_name = "low_left_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 3

[Main.cameras."pci-0000:35:00.3-usb-0:1.4:1.0"]
link_name = "low_right_camera"
focal_length_x_px = 1100
focal_length_y_px = 1100
# stream_index = 5

[Main.cameras."pci-0000:34:00.4-usb-0:2.4:1.0"]
link_name = "back_camera"
focal_length_x_px = 600
focal_length_y_px = 600
stream_index = 7

[Main.depth_cameras."044422250424"]
link_name = "upper_depth_camera"
stream_index = 1

[Main.depth_cameras."309622300683"]
link_name = "lower_depth_camera"
stream_index = 4
depth_enabled = false

[Main.apriltags."70"]
tag_position = [0.0, 0.6477, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.198

[Main.apriltags."82"]
tag_position = [2.0, 0.0, 3.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.161

[Main.apriltags."95"]
tag_position = [0.3, 0.0, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.18

[Main.apriltags."16"]
tag_position = [0,0,0]
forward_axis = [0,1,0]
tag_width = 0.215

[Main.apriltags."25"]
tag_position = [0,0,0]
forward_axis = [0,1,0]
tag_width = 0.215

[Main.v3pico]
serial = "1"

[[Main.v3pico.imus]]
link_name = "imu0"

[[Main.v3pico.imus]]
link_name = "imu1"

[[Main.v3pico.imus]]
link_name = "imu2"

[[Main.v3pico.imus]]
link_name = "imu3"

[Main.vesc]
speed_multiplier = 2250.0

[[Main.vesc.pairs]]
id1 = 75
id2 = 110
mask1 = "Right"
mask2 = "Right"

[[Main.vesc.pairs]]
id1 = 63
id2 = 74
mask1 = "Left"
mask2 = "Left"

[Main.imu_correction]
accelerometer_bias = [0.002709543940755004, -0.22645730987989818, -0.004565496211130569]
gyroscope_bias = [-0.000000000000000027465820312500003, -0.000000000000000027465820312500003, -0.000000000000000027465820312500003]
accelerometer_scale = [1.0, 1.0, 1.0]
gyroscope_scale = [1.0, 1.0, 1.0]
with_scaling = false
misalignment = [-0.010071734378705816, -0.0000005474737870781548, -0.005931499949072841, 0.999931686403956]
