[Main]
robot_layout = "robot-layout/lunabot.json"

[Main.cameras."0"]
link_name = "left_arm_camera"
focal_length_x_px = 440
focal_length_y_px = 440

[Main.cameras."1"]
link_name = "right_arm_camera"
focal_length_x_px = 685
focal_length_y_px = 685

[Main.depth_cameras."309622300683"]
link_name = "upper_depth_camera"
stream_index = 1

[Main.depth_cameras."044422250424"]
link_name = "lower_depth_camera"
stream_index = 4

[Main.cameras."2"]
link_name = "back_camera"
focal_length_x_px = 440
focal_length_y_px = 440

[Main.cameras."3"]
link_name = "low_left_camera"
focal_length_x_px = 440
focal_length_y_px = 440

[Main.cameras."4"]
link_name = "low_right_camera"
focal_length_x_px = 685
focal_length_y_px = 685

[Main.apriltags."1"]
tag_position = [0.0, 0.6477, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.104775

[Main.apriltags."13"]
tag_position = [-1.83, 0.75, 0.127]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.15

[Main.apriltags."26"]
tag_position = [0.65, 0.7, 0.93]
forward_axis = [-1.0, 0.0, 0.0]
tag_width = 0.152

[Main.v3pico]
serial = "1"
[[Main.v3pico.imus]]
link_name = "imu0"

[[Main.v3pico.imus]]
link_name = "imu1"

[[Main.v3pico.imus]]
link_name = "imu2"

[[Main.v3pico.imus]]
link_name = "imu3"

[Main.vesc]
speed_multiplier = 2250.0

[[Main.vesc.pairs]]
id1 = 75
id2 = 110
mask1 = "Right"
mask2 = "Right"

[[Main.vesc.pairs]]
id1 = 63
id2 = 74
mask1 = "Left"
mask2 = "Left"
