[Main]
robot_layout = "robot-layout/ele.json"
lunabase_address = "192.168.0.100"

[Main.cameras."pci-0000:35:00.0-usb-0:1:1.0"]
link_name = "right_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 2

[Main.cameras."pci-0000:34:00.3-usb-0:4:1.0"]
link_name = "back_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 4

[Main.depth_cameras."044422250424"]
link_name = "depth_camera"
stream_index = 1

[Main.cameras."pci-0000:34:00.4-usb-0:1.4.4:1.0"]
link_name = "left_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 0

[Main.apriltags."1"]
tag_position = [0.0, 0.6477, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.104775

[Main.apriltags."13"]
tag_position = [-1.83, 0.75, 0.127]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.15

[Main.apriltags."26"]
tag_position = [0.65, 0.7, 0.93]
forward_axis = [-1.0, 0.0, 0.0]
tag_width = 0.152

[Main.imus."21"]
link_name = "imu_21"

[Main.imus."42"]
link_name = "imu_42"

[Main.vesc]
speed_multiplier = 0.2

[[Main.vesc.pairs]]
id1 = 4
id2 = 87
mask1 = "Left"
mask2 = "Right"
