[Main]
robot_layout = "robot-layout/ele.json"

# [Main.rerun_viz."Viz"."Minimal"]

[Main.cameras."pci-0000:35:00.0-usb-0:1:1.0"]
link_name = "right_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 2

[Main.cameras."pci-0000:34:00.3-usb-0:4:1.0"]
link_name = "back_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 4

[Main.depth_cameras."044422250424"]
link_name = "depth_camera"
stream_index = 1

[Main.cameras."pci-0000:34:00.4-usb-0:1.1:1.0"]
link_name = "left_camera"
focal_length_x_px = 805
focal_length_y_px = 805
stream_index = 0

[Main.apriltags."1"]
tag_position = [0.0, 0.6477, 0.0]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.104775

[Main.apriltags."13"]
tag_position = [-1.83, 0.75, 0.127]
forward_axis = [0.0, 0.0, 1.0]
tag_width = 0.15

[Main.apriltags."26"]
tag_position = [0.65, 0.7, 0.93]
forward_axis = [-1.0, 0.0, 0.0]
tag_width = 0.152

[Main.v3pico]
serial = "1"
[[Main.v3pico.imus]]
link_name = "imu0"

[[Main.v3pico.imus]]
link_name = "imu1"

[[Main.v3pico.imus]]
link_name = "imu2"

[[Main.v3pico.imus]]
link_name = "imu3"

[Main.imu_correction]
accelerometer_bias = [0.000014598908463930101, 0.0017554738784322087, -0.0011911207615312067]
# the gyroscope actually does have enough additive bias not related to misalignment for it to be problematic
gyroscope_bias = [0.0006571120908115184, 0.004827296195746945, 0.00391800269744208]
accelerometer_scale = [1.0006693944778715, 1.0, 1.000337980374186]
gyroscope_scale = [1.0000005396753637, 1.0000079263524984, 1.0000176571997035]
with_scaling = false
misalignment = [-0.025058877215028884, 0.00000045302256055162416, -0.0003060294069638255, 0.9996859301893365]


[Main.vesc]
speed_multiplier = 0.2

[[Main.vesc.pairs]]
id1 = 4
id2 = 87
mask1 = "Left"
mask2 = "Right"

[Main.actuator_controller_info]
serial = "1"
