name: build_windows

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  default:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install the shim for pthread
      uses: lukka/run-vcpkg@v7
      id: vcpkg
      with:
        vcpkgArguments: 'pthread'
        vcpkgTriplet: 'x64-windows-static'
        vcpkgDirectory: '${{runner.workspace}}/vcpkg'
        vcpkgGitCommitId: '57bd7102d9fd880daa1b0958692294c4a125f6d8'
    - name: Check linking
      run: cargo test
      env:
        APRILTAG_SYS_WINDOWS_PTHREAD_INCLUDE_DIR: '${{steps.vcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT}}\installed\x64-windows-static\include'
        APRILTAG_SYS_WINDOWS_PTHREAD_STATIC_LIB: '${{steps.vcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT}}\installed\x64-windows-static\lib\pthreadVC3.lib'
