[package]
name = "lunaserver-web-host"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
tokio = { version = "1.43.0", features = ["process", "rt-multi-thread"] }
