name: build and release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: Export Lunabase Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build_lunabase
      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3-stable
          export-templates: true
      - run: godot --headless --export-release "Windows Desktop" lunabase/Lunabase.exe
        working-directory: godot/lunabase
      - name: Compress Directory
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./godot/lunabase/lunabase
          format: zip
      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            godot/lunabase/lunabase.zip
