name: build and release

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: Export Lunabase Windows
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3
      - name: Build Lunabase Lib
        run: cargo make build_lunabase
      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.3-stable
          export-templates: true
      - name: Create Export Directory
        run: mkdir godot/lunabase/lunabase
      - name: Export Lunabase Windows
        run: godot --headless --export-release "Windows Desktop" lunabase/Lunabase.exe
        working-directory: godot/lunabase
      - name: Archive Lunabase Windows
        run: 7z a -tzip lunabase_windows.zip ./godot/lunabase/lunabase/
      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./lunabase_windows.zip
